import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Club Name Here",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row justify-between gap-9 p-12">
          <ul className="flex flex-row gap-8">
            <li><Link href="/" className="hover:underline underline-offset-4">Home</Link></li>
            <li><Link href="/about" className="hover:underline underline-offset-4">About</Link></li>
            <li><Link href="/gallery" className="hover:underline underline-offset-4">Gallery</Link></li>
          </ul>
          <Link href="/login" className="hover:underline underline-offset-4">Log In</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
