import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { logout } from "@/actions/auth";
import { useEffect, useState } from "react";
import { verifyAuth } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Club Name Here",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,}: Readonly<{ children: React.ReactNode; }>) {

  /*
    TODO: 
    implement a way to conditionally render "Login" / "Logout" based on when a user is logged in or logged out. 
  */
  const isLoggedIn = await verifyAuth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row justify-between gap-9 p-12">
          <ul className="flex flex-row gap-8">
            <li><Link href="/" className="hover:underline underline-offset-4">Home</Link></li>
            <li><Link href="/about" className="hover:underline underline-offset-4">About</Link></li>
            <li><Link href="/gallery" className="hover:underline underline-offset-4">Gallery</Link></li>
          </ul>
          <div className="flex justify-center items-center gap-8">
            <Link href="/new-post" className="bg-white text-black p-2 rounded hover:scale-95 transition duration-200">Add to Gallery</Link>
            {
            /* Login / Logout */
              !isLoggedIn ? (
                <form action={logout}>
                  <button className="hover:underline underline-offset-4">Logout</button>
                </form>
              ) : (
                <Link href="/login" className="hover:underline underline-offset-4">Log In</Link>
              )
            }
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
